DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 128
  TEST:
    BATCH_SIZE: 64

DATALOADER:
  NUM_WORKERS: 8

OPTIM:
  NAME: "sgd"
  MAX_EPOCH: 50
  LR_SCHEDULER: "cosine"


# MODEL:
#   HEAD:
#     NAME: "se_attn_sr"